name: GitHub CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew assembleRelease ktlintCheck lintRelease testReleaseUnitTest -s
      - name: Upload coverage reports
        # Uploads all the coverage reports to Codecov.io:
        # -Z -> if the upload of a report fails, the build fails too
        # -s -> searches in the paths in which CoveragePlugin generates the coverage reports
        # -f -> uploads the XML files found in the search paths (specified with -s)
        # -X -> excludes the tools not needed by this project
        run: bash <(curl -s https://codecov.io/bash) -Z -s "**/build/coverageReport/test*Coverage/test*Coverage.xml" -f "*.xml" -X gcov -X coveragepy -X xcode -X gcovout
  test1:
    name: test 1/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Run tests on API 16, 17, 18, 19
        env:
          ROBOLECTRIC_MIN_API: 16
          ROBOLECTRIC_MAX_API: 19
        run: ./ci/run-tests.sh
  test2:
    name: test 2/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Run tests on API 21, 22, 23, 24
        env:
          ROBOLECTRIC_MIN_API: 21
          ROBOLECTRIC_MAX_API: 24
        run: ./ci/run-tests.sh
  test3:
    name: test 3/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Run tests on API 25, 26, 27, 28
        env:
          ROBOLECTRIC_MIN_API: 25
          ROBOLECTRIC_MAX_API: 28
        run: ./ci/run-tests.sh