name: Build

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew assembleRelease ktlintCheck lintRelease testReleaseUnitTest -s
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3.1.4
        with:
          files: "**/build/coverageReport/test*Coverage/test*Coverage.xml"
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
