name: Test

on: workflow_call

jobs:
  test1:
    name: test 1/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run tests on API 19, 21, 23
        run: ./ci/run-tests.sh -Probolectric.enabledSdks=19,21,23
  test2:
    name: test 2/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run tests on API 24, 26, 28
        run: ./ci/run-tests.sh -Probolectric.enabledSdks=24,26,28
  test3:
    name: test 3/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run tests on API 29, 30, 31, 33
        run: ./ci/run-tests.sh -Probolectric.enabledSdks=29,30,31,33
